pub const MAX_PAYLOAD_SIZE: usize = 16384;

pub const DOUBLE_OPERATORS: [&str; 9] = ["&&", "||", "<<", ">>", "==", "!=", "()", "<=", ">="];

pub fn operator_value(op: &str) -> Option<u16> {
    Some(match op {
        "+" => 0x02E8,
        "-" => 0x03E8,
        "*" => 0x04E8,
        "/" => 0x05E8,
        "==" => 0x06E8,
        "!=" => 0x07E8,
        "<" => 0x08E8,
        ">" => 0x09E8,
        "<=" => 0xA8E8,
        ">=" => 0xA9E8,
        "&&" | "AND" => 0xAAE8,
        "||" | "OR" => 0xBBE8,
        "&" => 0x0AE8,
        "|" => 0x0BE8,
        ">>" => 0x0CE8,
        "<<" => 0x0DE8,
        "%" => 0x0EE8,
        "^" => 0xE80F,
        _ => return None,
    })
}

pub fn reserved_variable_value(name: &str) -> Option<u16> {
    Some(match name {
        "$_BUTTON_ENABLED" => 0x4280,
        "$_BUTTON_USER_DEFINED" => 0x4281,
        "$_BUTTON_PUSH_RECEIVED" => 0x4284,
        "$_LED_SHOW_STORAGE_ACTIVITY" => 0x4285,
        "$_SYSTEM_LEDS_ENABLED" => 0x4286,
        "$_STORAGE_LEDS_ENABLED" => 0x4287,
        "$_INJECTING_LEDS_ENABLED" => 0x4288,
        "$_EXFIL_LEDS_ENABLED" => 0x4289,
        "$_CAPSLOCK_ON" => 0x4290,
        "$_NUMLOCK_ON" => 0x4291,
        "$_SCROLLLOCK_ON" => 0x4292,
        "$_SAVED_CAPSLOCK_ON" => 0x4293,
        "$_SAVED_NUMLOCK_ON" => 0x4294,
        "$_SAVED_SCROLLLOCK_ON" => 0x4295,
        "$_RECEIVED_HOST_LOCK_LED_REPLY" => 0x4296,
        "$_EXFIL_MODE_ENABLED" => 0x4297,
        "$_STORAGE_ACTIVITY_TIMEOUT" => 0x4298,
        "$_BUTTON_TIMEOUT" => 0x4299,
        "$_PAYLOAD_PARSE_SPEED" => 0x429A,
        "$_CURRENT_VID" => 0x429B,
        "$_CURRENT_PID" => 0x429C,
        "$_OS" => 0x429D,
        "$_HOST_CONFIGURATION_REQUEST_COUNT" => 0x429F,
        "$_CURRENT_ATTACKMODE" => 0x42A0,
        "$_JITTER_ENABLED" => 0x42A2,
        "$_JITTER_MAX" => 0x42A3,
        "$_STORAGE_ACTIVE" => 0x42A4,
        "$_RANDOM_INT" => 0x42A8,
        "$_RANDOM_MIN" => 0x42F0,
        "$_RANDOM_MAX" => 0x42F1,
        "$_RANDOM_SEED" => 0x42F2,
        "$_RANDOM_UINT16" => 0x42F3,
        "$_RANDOM_ASCII_LOWER_LETTER" => 0x42F4,
        "$_RANDOM_ASCII_UPPER_LETTER" => 0x42F5,
        "$_RANDOM_ASCII_LETTER" => 0x42F6,
        "$_RANDOM_ASCII_NUMBER" => 0x42F7,
        "$_RANDOM_ASCII_SPECIAL" => 0x42F8,
        "$_RANDOM_ASCII_CHAR" => 0x42F9,
        "$_RANDOM_LOWER_LETTER_KEYCODE" => 0x42FA,
        "$_RANDOM_UPPER_LETTER_KEYCODE" => 0x42FB,
        "$_RANDOM_LETTER_KEYCODE" => 0x42FF,
        "$_RANDOM_NUMBER_KEYCODE" => 0x42FC,
        "$_RANDOM_SPECIAL_KEYCODE" => 0x42FD,
        "$_RANDOM_CHAR_KEYCODE" => 0x42FE,
        _ => return None,
    })
}

pub fn reserved_constant_value(name: &str) -> Option<u16> {
    Some(match name {
        "FALSE" => 0x4267,
        "TRUE" => 0x4268,
        "WINDOWS" => 0x4269,
        "MACOS" => 0x4270,
        "LINUX" => 0x4271,
        "ANDROID" => 0x4272,
        "IOS" => 0x4273,
        "CHROMEOS" => 0x4274,
        _ => return None,
    })
}

pub fn builtin_value(name: &str) -> Option<u16> {
    Some(match name {
        "RESET" => 0xED04,
        "KEY_HOLD" => 0xF8FF,
        "KEY_RELEASE" => 0xE8EE,
        "DISABLE_BUTTON" => 0xEEEB,
        "ENABLE_BUTTON" => 0xEEEC,
        "RESTART_PAYLOAD" => 0xF1EA,
        "STOP_PAYLOAD" => 0xF1EB,
        "LED_OFF" => 0xEDEA,
        "LED_G" | "LED_GREEN" => 0xEDEB,
        "LED_R" | "LED_RED" => 0xEDEC,
        "ENABLE_SYSTEM_LEDS" => 0xED01,
        "DISABLE_SYSTEM_LEDS" => 0xED02,
        "SAVE_HOST_KEYBOARD_LOCK_STATE" => 0xEBEA,
        "RESTORE_HOST_KEYBOARD_LOCK_STATE" => 0xEBEB,
        "WAIT_FOR_BUTTON_PRESS" => 0xEAEA,
        "SAVE_ATTACKMODE" => 0xE9EA,
        "RESTORE_ATTACKMODE" => 0xE9EB,
        "WAIT_FOR_CAPS_ON" => 0xEA01,
        "WAIT_FOR_CAPS_OFF" => 0xEA02,
        "WAIT_FOR_CAPS_CHANGE" => 0xEA03,
        "WAIT_FOR_NUM_ON" => 0xEA04,
        "WAIT_FOR_NUM_OFF" => 0xEA05,
        "WAIT_FOR_NUM_CHANGE" => 0xEA06,
        "WAIT_FOR_SCROLL_ON" => 0xEA07,
        "WAIT_FOR_SCROLL_OFF" => 0xEA08,
        "WAIT_FOR_SCROLL_CHANGE" => 0xEA09,
        "WAIT_FOR_STORAGE_ACTIVITY" => 0xEAEE,
        "WAIT_FOR_STORAGE_INACTIVITY" => 0xEAEF,
        "HIDE_PAYLOAD" => 0xE9F8,
        "RESTORE_PAYLOAD" => 0xE9F9,
        _ => return None,
    })
}
